In [ ]:
import pandas as pd

df = pd.read_csv(
    "../data/cleaned_stock_data.csv"
)

df['Date'] = pd.to_datetime(
    df['Date']
)

df.head()

,Date,Close,High,Low,Open,Volume,Stock,Year,Month,Quarter,Day
0,2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,AAPL,2020,1,1,2
1,2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,AAPL,2020,1,1,3
2,2020-01-06,72.201416,72.239950,70.503554,70.754021,118387200,AAPL,2020,1,1,6
3,2020-01-07,71.861832,72.466315,71.642674,72.211033,108872000,AAPL,2020,1,1,7
4,2020-01-08,73.017853,73.318893,71.565636,71.565636,132079200,AAPL,2020,1,1,8

In [5]:
# Sorting the data

df = df.sort_values(
    ['Stock','Date']
)

df.head()

,Date,Close,High,Low,Open,Volume,Stock,Year,Month,Quarter,Day
0,2020-01-02,72.333885,72.394093,71.091191,71.344062,135480400,AAPL,2020,1,1,2
1,2020-01-03,71.630638,72.389257,71.406666,71.563205,146322800,AAPL,2020,1,1,3
2,2020-01-06,72.201416,72.239950,70.503554,70.754021,118387200,AAPL,2020,1,1,6
3,2020-01-07,71.861832,72.466315,71.642674,72.211033,108872000,AAPL,2020,1,1,7
4,2020-01-08,73.017853,73.318893,71.565636,71.565636,132079200,AAPL,2020,1,1,8

In [6]:
# DAILY RETURN measures % change in price.
# RETURN = (Pt-(Pt-1)/(Pt-1))

df['Daily_Return']=(df.groupby('Stock')['Close']).pct_change()

In [7]:
df[['Date','Stock','Close','Daily_Return']].head()

        Date Stock      Close  Daily_Return
0 2020-01-02  AAPL  72.333885           NaN
1 2020-01-03  AAPL  71.630638     -0.009722
2 2020-01-06  AAPL  72.201416      0.007968
3 2020-01-07  AAPL  71.861832     -0.004703
4 2020-01-08  AAPL  73.017853      0.016087

In [8]:
# Volatility => higher volatitlity -> higher risk
# 30 day rolling risk

df['Volatility']=(df.groupby('Stock')['Daily_Return'].transform(lambda x:x.rolling(30).std()))

In [9]:
df[['Stock','Volatility']].tail()

     Stock  Volatility
6285  TSLA    0.039291
6286  TSLA    0.037305
6287  TSLA    0.038926
6288  TSLA    0.037692
6289  TSLA    0.038288

In [10]:
# Moving average (50 days MA)

df['MA50'] = (df.groupby('Stock')['Close'].transform(lambda x:x.rolling(50).mean()))

In [11]:
# 200 days MA

df['MA200'] = (df.groupby('Stock')['Close'].transform(lambda x:x.rolling(200).mean()))

In [12]:
# CUMMULATIVE RETURN -> Shows total growth over time.

df['Cumulative_Return'] = (1+df['Daily_Return']).groupby(df['Stock']).cumprod()

In [13]:
df[['Stock','Cumulative_Return']].tail()

     Stock  Cumulative_Return
6285  TSLA          16.116302
6286  TSLA          15.832171
6287  TSLA          15.048808
6288  TSLA          14.552015
6289  TSLA          14.078929

In [14]:
#  Rolling Average Volume 30 days

df['Avg_Volume_30'] = (df.groupby('Stock')['Volume'].transform(lambda x:x.rolling(30).mean()))

In [15]:
# Annualized Volatility

import numpy as np

df['Annualized_Volatility'] = (df['Volatility']*np.sqrt(252))

In [16]:
# Sharpe Ratio 

risk_free_rate = 0.02

mean_return = (df.groupby('Stock')['Daily_Return']
                .transform('mean'))
                
df['Sharpe_Ratio'] = (mean_return-risk_free_rate/252)/df['Volatility']

In [17]:
# Checking nulls

df.isnull().sum()

Date                        0
Close                       0
High                        0
Low                         0
Open                        0
Volume                      0
Stock                       0
Year                        0
Month                       0
Quarter                     0
Day                         0
Daily_Return                6
Volatility                180
MA50                      294
MA200                    1194
Cumulative_Return           6
Avg_Volume_30             174
Annualized_Volatility     180
Sharpe_Ratio              180
dtype: int64

In [18]:
df.dropna(
    inplace=True
)

In [19]:
df.isnull().sum()

Date                     0
Close                    0
High                     0
Low                      0
Open                     0
Volume                   0
Stock                    0
Year                     0
Month                    0
Quarter                  0
Day                      0
Daily_Return             0
Volatility               0
MA50                     0
MA200                    0
Cumulative_Return        0
Avg_Volume_30            0
Annualized_Volatility    0
Sharpe_Ratio             0
dtype: int64

In [ ]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Stock', 'Year',
       'Month', 'Quarter', 'Day', 'Daily_Return', 'Volatility', 'MA50',
       'MA200', 'Cumulative_Return', 'Avg_Volume_30', 'Annualized_Volatility',
       'Sharpe_Ratio'],
      dtype='str')

In [21]:
df.to_csv(

"../data/stock_features.csv",

index=False

)